# # Wildcard certificate for *.diagon.ally (legacy domain)
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-cert-diagon
#   namespace: external-resources
# spec:
#   secretName: diagon-ally-tls
#   duration: 2160h # 90 days
#   renewBefore: 360h # 15 days
#   issuerRef:
#     name: vault-issuer-diagon
#     kind: Issuer
#   commonName: <path:secrets/data/infra/network/prod#wildcard_domain_diagon>
#   dnsNames:
#   - <path:secrets/data/infra/network/prod#wildcard_domain_diagon>
#   - <path:secrets/data/infra/network/prod#base_domain_diagon>
# ---
# Wildcard certificate for *.styx.river (new domain)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-styx
  namespace: external-resources
spec:
  secretName: styx-river-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: vault-issuer-styx
    kind: Issuer
  commonName: <path:secrets/data/infra/network/prod#wildcard_domain_styx>
  dnsNames:
  - <path:secrets/data/infra/network/prod#wildcard_domain_styx>
  - <path:secrets/data/infra/network/prod#base_domain_styx>
